[match]
dot = true

[args.linters]
yamllint = ["--strict"]
tombi = ["--error-on-warnings"]

[formatters]
prettier = ["**/*.yml", "**/*.json"]
tombi = ["**/*.toml"]

[linters]
typos = ["**/*"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
tombi = ["**/*.toml"]
