[match]
dot = true

[pull_request]
check_title = true

[args.linters]
yamllint = ["--strict"]
tombi = ["--error-on-warnings"]

[formatters]
prettier = ["**/*.yml", "**/*.json"]
tombi = ["**/*.toml"]

[linters]
typos = ["**/*", "![a-z0-9-]+/**"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
tombi = ["**/*.toml"]
