[match]
dot = true

[pull_request]
check_title = true
# https://codeql.github.com/docs/codeql-overview/supported-languages-and-frameworks/#languages-and-compilers
detect_changes = [".github/workflows/*.yml"]

[args.linters]
yamllint = ["--strict"]
tombi = ["--error-on-warnings"]

[formatters]
prettier = ["**/*.yml", "**/*.json"]
tombi = ["**/*.toml"]

[linters]
typos = ["**/*", "![a-z0-9-]+/**"]
yamllint = ["**/*.yml"]
actionlint = [".github/workflows/*.yml"]
tombi = ["**/*.toml"]
