docs:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/PULL_REQUEST_TEMPLATE.md'
          - 'LICENSE'

chore:
  - changed-files:
      - any-glob-to-any-file:
          - '*/**'
          - '.github/CODEOWNERS'
          - '.gitignore'
          - '.git-blame-ignore-revs'
          - '.editorconfig'
          # NOTE: `*.foo`, `/*.foo`, and `./*.foo` will trigger a recursive glob match.
          - '.commitlintrc.json'
          - '.prettierrc.yml'
          - '.typos.toml'
          - '.yamllint.yml'
          - 'changelogithub.config.json'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*.yml'
          - '.github/dco.yml'
          - '.github/dependabot.yml'
          - '.github/labeler.yml'
          - '.github/title-labeler.yml'
          - '.github/insight.toml'
