revert:
  - '/^revert(?:\(([^)]+)\))?:\s.+/'
refactor:
  - '/^refactor(?:\(([^)]+)\))?:\s.+/'
style:
  - '/^style(?:\(([^)]+)\))?:\s.+/'
breaking:
  - '/^(revert|refactor)(?:\(([^)]+)\))?!:\s.+/'
docs:
  - '/^docs(?:\(([^)]+)\))?:\s.+/'
chore:
  - '/^chore(?:\(([^)]+)\))?:\s.+/'
ci:
  - '/^ci(?:\(([^)]+)\))?:\s.+/'
